"""Generate before/after query-count evidence for Section 1 using django-silk.

Seeds a customer with many orders, drives both endpoints through the full
middleware stack (so SilkyMiddleware records them), then reads the query counts
that silk itself captured and writes them to docs/section1/silk-evidence.md.

    python manage.py capture_silk_evidence --orders 200
"""

from pathlib import Path

from django.conf import settings
from django.core.management import call_command
from django.core.management.base import BaseCommand
from django.test import Client

from silk.models import Request as SilkRequest


class Command(BaseCommand):
    help = "Capture django-silk query-count evidence for the orders summary endpoint."

    def add_arguments(self, parser):
        parser.add_argument("--orders", type=int, default=200)
        parser.add_argument("--items", type=int, default=3)

    def handle(self, *args, **options):
        n_orders = options["orders"]

        # Fresh data set for a clean comparison.
        from orders.models import Customer, Order, OrderItem
        Customer.objects.all().delete()  # cascades to orders + items
        SilkRequest.objects.all().delete()

        call_command("seed_orders", orders=n_orders, items=options["items"],
                     verbosity=0)
        customer = Customer.objects.latest("id")

        client = Client()
        broken_path = f"/api/orders/summary/broken/?customer_id={customer.id}"
        fixed_path = f"/api/orders/summary/?customer_id={customer.id}"
        client.get(broken_path)
        client.get(fixed_path)

        def queries_for(path_prefix):
            req = (SilkRequest.objects
                   .filter(path="/api/orders/summary/broken/"
                           if "broken" in path_prefix else "/api/orders/summary/")
                   .order_by("-start_time")
                   .first())
            return req.num_sql_queries if req else None

        broken_q = queries_for("broken")
        fixed_q = queries_for("fixed")

        out = Path(settings.BASE_DIR) / "docs" / "section1" / "silk-evidence.md"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(_render(n_orders, options["items"], broken_q, fixed_q))

        self.stdout.write(self.style.SUCCESS(
            f"Recorded via django-silk with {n_orders} orders:\n"
            f"  BROKEN /api/orders/summary/broken/  -> {broken_q} SQL queries\n"
            f"  FIXED  /api/orders/summary/         -> {fixed_q} SQL queries\n"
            f"Evidence written to {out}"
        ))


def _render(n_orders, n_items, broken_q, fixed_q):
    reduction = (
        f"{(1 - fixed_q / broken_q) * 100:.1f}%"
        if broken_q and fixed_q else "n/a"
    )
    return f"""# Section 1 — django-silk query-count evidence

Generated by `python manage.py capture_silk_evidence --orders {n_orders} --items {n_items}`.

The same customer ({n_orders} orders, {n_items} items each) was requested through
both endpoints. Query counts below are the values **django-silk recorded**
(`silk.models.Request.num_sql_queries`) while the requests ran through
`SilkyMiddleware`. Browse them interactively at `/silk/`.

| Endpoint | View | SQL queries |
| --- | --- | --- |
| `GET /api/orders/summary/broken/` | `BrokenOrderSummaryView` | **{broken_q}** |
| `GET /api/orders/summary/`        | `FixedOrderSummaryView`  | **{fixed_q}** |

**Reduction: {reduction}.**

The broken endpoint's count tracks `1 + 3N` (one base query plus a customer
lookup, a `COUNT(*)`, and an items fetch per order). The fixed endpoint collapses
to a small constant because `select_related("customer")` joins the to-one FK and
`.annotate(Count/Sum)` computes the aggregates in a single `GROUP BY` query.

Re-run this command any time to regenerate the numbers from a clean state.
"""
